---
# tasks file for ansible-role-template
  - name: Ensure clone_path exists
    file:
      path: "{{ clone_path }}"
      state: directory
      owner: "{{ lookup('env', 'USER') }}"
      mode: '0755'
    become: yes

  - name: Include ssh.yml task in play
    ansible.builtin.include: ssh.yml

  - name: Include https.yml task in play
    ansible.builtin.include: https.yml

  - name: Ambigous settings detected.
    debug:
      msg: You want to split all in everything, that's weird. Please correct split_by variables.
    when: 
      - split_by_project == true
      - split_by_source == true
      - split_by_user == true